optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: false
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 2023
  patience: 5

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_agcf
  name: amazon
  mat_type: uai
  pre_norm: true

model:
  name: simgcl_a
  # general parameters here
  keep_rate: 1.0
  embedding_size: 64

  # dataset-specific hyper-parameter here
  layer_num: 3
  reg_weight: 1.0e-5
  cl_weight: 1.0e-1
  temperature: 0.2
  eps: 0.9
  # for amazon
  amazon:
    keep_rate: 0.9
    layer_num: 3
    reg_weight: 1.0e-5
    cl_weight: 1.0e-1
    temperature: 0.2
    eps: 0.1
  # for yelp
  yelp:
    layer_num: 3
    reg_weight: 1.0e-5
    cl_weight: 1.0e-1
    temperature: 0.2
    eps: 0.9
  # for steam
  steam:
    layer_num: 3
    reg_weight: 1.0e-5
    cl_weight: 1.0e-1
    temperature: 0.5
    eps: 0.2
  Office:
    layer_num: 3
    reg_weight: 1.0e-5
    cl_weight: 1.0e-1
    temperature: 0.2
    eps: 0.9
